FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY cart.html /usr/share/nginx/html/cart.html
COPY orders.html /usr/share/nginx/html/orders.html
COPY cart.js /usr/share/nginx/html/cart.js
COPY orders.js /usr/share/nginx/html/orders.js
COPY script.js /usr/share/nginx/html/script.js
COPY style.css /usr/share/nginx/html/style.css
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]